-- Add a `source` column to sentence_bank so the read path can prefer
-- LLM-generated example sentences over subtitle-extracted ones.
--
-- Existing rows were all extracted from movie scripts via OpenSubtitles,
-- so they default to 'subtitle'. New rows generated by the LLM worker
-- will be inserted with source='llm'. Tatoeba / public-domain fallbacks
-- can use the remaining enum values later.
--
-- The composite (movie_id, source) index supports the new query pattern
-- in /sentences/batch which fetches LLM rows for a movie first and falls
-- back to subtitle rows when none exist.
--
-- Run: psql "$DATABASE_URL" -f prisma/migrations_manual/2026_05_14_sentence_bank_source.sql
-- Then: prisma generate

BEGIN;

-- Idempotent enum creation: Postgres has no CREATE TYPE IF NOT EXISTS, so
-- wrap it in a DO block that checks pg_type first.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'sentencesource') THEN
    CREATE TYPE sentencesource AS ENUM ('subtitle', 'llm', 'tatoeba', 'public_domain');
  END IF;
END
$$;

ALTER TABLE sentence_bank
  ADD COLUMN IF NOT EXISTS source sentencesource NOT NULL DEFAULT 'subtitle';

CREATE INDEX IF NOT EXISTS ix_sentence_bank_movie_source
  ON sentence_bank (movie_id, source);

COMMIT;
