# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

require_relative '../node_modules/expo/scripts/autolinking'

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'WordWiseMobile' do
  use_expo_modules!
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Fix fmt consteval compilation issue with Xcode 16+
    # Patch the fmt base.h header to force disable consteval
    fmt_base_h = File.join(installer.sandbox.root, 'fmt', 'include', 'fmt', 'base.h')
    if File.exist?(fmt_base_h)
      content = File.read(fmt_base_h)
      patched_content = content.gsub(
        /\/\/ Detect consteval.*?#define FMT_USE_CONSTEVAL 0\n#endif/m,
        "// Detect consteval, C++20 constexpr extensions and std::is_constant_evaluated.\n// Force disable consteval due to Xcode 16+ compatibility issues\n#define FMT_USE_CONSTEVAL 0"
      )
      File.write(fmt_base_h, patched_content)
      Pod::UI.puts "[fmt] Patched base.h to disable consteval".green
    end
  end
end
