import { StyleSheet } from "react-native";
import { colors } from "../theme/palette";

// App-wide shared styles for main App.tsx screens/components.
// Gradually migrate styles out of this file into per-component co-located
// StyleSheets. Shared chrome (header, button) stays here; component-
// specific styles live with the component (e.g. WordRow/IdiomRow row styles
// live in components/vocabulary/rowStyles.ts).
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  viewAsBadge: {
    backgroundColor: '#F4A261',
    paddingVertical: 6,
    paddingHorizontal: 12,
    alignItems: 'center',
  },
  viewAsBadgeText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
  },
  reviewCta: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#7C5CBF',
    borderRadius: 14,
    padding: 16,
    shadowColor: '#7C5CBF',
    shadowOpacity: 0.2,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
  },
  reviewCtaLeft: { flex: 1 },
  reviewCtaTitle: { fontSize: 16, fontWeight: '700', color: '#FFFFFF' },
  reviewCtaSubtitle: { fontSize: 13, color: 'rgba(255,255,255,0.8)', marginTop: 2 },
  reviewCtaWrapper: { marginHorizontal: 16, marginTop: 20 },
  reviewCtaArrow: { fontSize: 22, color: '#FFFFFF', fontWeight: '700', marginLeft: 8 },
  homeNavToggleWrapper: {
    flexDirection: 'row',
    alignSelf: 'center',
    marginTop: 14,
    backgroundColor: colors.paper,
    borderRadius: 12,
    padding: 4,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
  },
  homeNavToggleBtn: {
    paddingHorizontal: 14,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
  },
  homeNavToggleText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#7C5CBF',
  },
  todayCard: {
    marginHorizontal: 16,
    marginTop: 16,
    borderRadius: 16,
    overflow: 'hidden',
  },
  todayCardFace: {
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E8E8EC',
    backfaceVisibility: 'hidden',
  },
  todayCardBack: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
  },
  todayCardInner: {
    padding: 20,
  },
  todayHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
  todayLabel: { fontSize: 11, fontWeight: '700', color: '#7C5CBF', textTransform: 'uppercase', letterSpacing: 0.8 },
  todayMovie: { fontSize: 11, color: '#9AA0AE' },
  todayWord: { fontSize: 30, fontWeight: '800', color: '#1A1A2E', marginBottom: 2, letterSpacing: -0.3 },
  todayTapHint: { fontSize: 12, color: '#9AA0AE', marginTop: 4 },
  todayTranslation: { fontSize: 15, color: '#7C5CBF', fontWeight: '500', marginBottom: 12 },
  todaySentence: { fontSize: 13, color: '#4A4A5A', fontStyle: 'italic', lineHeight: 19, marginBottom: 4 },
  todayTranslatedSentence: { fontSize: 12, color: '#9AA0AE', lineHeight: 17, marginBottom: 14 },
  todaySaveBtn: {
    marginTop: 4,
    paddingVertical: 11,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: '#7C5CBF',
    alignItems: 'center',
  },
  todaySaveBtnSaved: { borderColor: '#4CAF9A', backgroundColor: '#F0FAF6' },
  todaySaveBtnText: { fontSize: 14, fontWeight: '700', color: '#7C5CBF' },
  todaySaveBtnTextSaved: { color: '#4CAF9A' },
  todayNudge: { fontSize: 12, color: '#7C5CBF', fontWeight: '500', marginTop: 10 },
  adBanner: {
    height: 60,
    marginHorizontal: 16,
    marginTop: 4,
    borderRadius: 10,
    backgroundColor: '#F0EDE8',
    borderWidth: 1,
    borderColor: '#E0DDD8',
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
  },
  adBannerText: { fontSize: 12, color: '#9AA0AE', fontWeight: '600', letterSpacing: 1, textTransform: 'uppercase' },
  centered: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  loginContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  logo: {
    fontSize: 36,
    fontWeight: '700',
    color: colors.primary,
    marginBottom: 8,
  },
  tagline: {
    fontSize: 16,
    color: colors.textSecondary,
    marginBottom: 48,
    textAlign: 'center',
  },
  formContainer: {
    width: '100%',
    gap: 12,
  },
  googleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.paper,
    paddingVertical: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 10,
  },
  googleIcon: {
    fontSize: 18,
    fontWeight: '700',
    color: '#4285F4',
  },
  googleButtonText: {
    fontSize: 16,
    fontWeight: '500',
    color: colors.text,
  },
  divider: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 8,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: colors.border,
  },
  dividerText: {
    paddingHorizontal: 16,
    color: colors.textSecondary,
    fontSize: 14,
  },
  input: {
    backgroundColor: colors.paper,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    paddingVertical: 14,
    paddingHorizontal: 16,
    fontSize: 16,
    color: colors.text,
  },
  primaryButton: {
    backgroundColor: colors.primary,
    paddingVertical: 16,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 8,
  },
  buttonDisabled: {
    opacity: 0.7,
  },
  primaryButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  switchButton: {
    alignItems: 'center',
    paddingVertical: 12,
  },
  switchButtonText: {
    color: colors.primary,
    fontSize: 14,
  },
  loginError: {
    color: colors.error,
    fontSize: 14,
    textAlign: 'center',
  },
  secondaryButton: {
    backgroundColor: colors.paper,
    paddingVertical: 16,
    borderRadius: 8,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  secondaryButtonText: {
    color: colors.textSecondary,
    fontSize: 16,
    fontWeight: '500',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: colors.paper,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: colors.primary,
  },
  logoutText: {
    fontSize: 14,
    color: colors.textSecondary,
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  languageButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.background,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 6,
  },
  adminButton: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  adminButtonText: {
    fontSize: 18,
    color: colors.primary,
    fontWeight: '600',
  },
  languageButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.primary,
  },
  languageDropdownIcon: {
    fontSize: 10,
    color: colors.textSecondary,
  },
  avatarButton: {
    padding: 2,
  },
  avatarImage: {
    width: 36,
    height: 36,
    borderRadius: 18,
  },
  avatarPlaceholder: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarInitial: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
  },
  dropdownMenu: {
    position: 'absolute',
    top: 60,
    right: 16,
    backgroundColor: colors.paper,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
    zIndex: 1000,
    minWidth: 180,
    maxHeight: 300,
    borderWidth: 1,
    borderColor: colors.border,
  },
  userDropdownMenu: {
    right: 16,
  },
  dropdownScroll: {
    maxHeight: 280,
  },
  dropdownItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    gap: 12,
  },
  dropdownItemActive: {
    backgroundColor: colors.background,
  },
  dropdownItemCode: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.primary,
    width: 28,
  },
  dropdownItemText: {
    fontSize: 14,
    color: colors.text,
  },
  dropdownItemIcon: {
    fontSize: 16,
  },
  dropdownUserInfo: {
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  dropdownUserName: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.text,
  },
  dropdownUserEmail: {
    fontSize: 13,
    color: colors.textSecondary,
    marginTop: 2,
  },
  dropdownDivider: {
    height: 1,
    backgroundColor: colors.border,
    marginVertical: 4,
  },
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: colors.paper,
    paddingHorizontal: 16,
    paddingBottom: 12,
    gap: 8,
  },
  tab: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: colors.background,
    alignItems: 'center',
  },
  tabActive: {
    backgroundColor: colors.primary,
  },
  tabText: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  tabTextActive: {
    color: '#fff',
  },
  scrollView: {
    flex: 1,
  },
  searchBarFixed: {
    position: 'absolute',
    left: 0,
    right: 0,
    zIndex: 300,
  },
  searchContainer: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 6,
    position: 'relative',
    zIndex: 200,
    overflow: 'visible',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  searchBrandLabel: {
    fontSize: 15,
    fontWeight: '800',
    color: colors.primary,
    letterSpacing: 0.5,
    marginRight: 2,
  },
  searchButton: {
    backgroundColor: colors.primary,
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchButtonText: {
    fontSize: 18,
  },
  searchInputWrapper: {
    flex: 1,
    position: 'relative',
    zIndex: 100,
  },
  autocompleteDropdown: {
    position: 'absolute',
    top: '100%',
    left: 0,
    right: 0,
    backgroundColor: colors.paper,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    zIndex: 100,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
  },
  recentlyViewedLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.textSecondary,
    letterSpacing: 0.5,
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 4,
    textTransform: 'uppercase',
  },
  seeAllButton: {
    paddingVertical: 12,
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  seeAllText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.primary,
  },
  searchClear: {
    position: 'absolute',
    right: 12,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    paddingHorizontal: 4,
  },
  searchClearText: {
    fontSize: 16,
    color: colors.textSecondary,
  },
  searchResultsList: {
    paddingHorizontal: 16,
  },
  searchResultItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  searchResultPoster: {
    width: 46,
    height: 69,
    borderRadius: 4,
  },
  searchResultInfo: {
    flex: 1,
    marginLeft: 12,
  },
  searchResultTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.text,
  },
  searchResultYear: {
    fontSize: 13,
    color: colors.textSecondary,
    marginTop: 2,
  },
  searchResultOverview: {
    fontSize: 12,
    color: colors.textSecondary,
    marginTop: 4,
    lineHeight: 16,
  },
  searchInput: {
    flex: 1,
    backgroundColor: colors.paper,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    color: colors.text,
    borderWidth: 1,
    borderColor: colors.border,
  },
  section: {
    paddingHorizontal: 16,
    marginBottom: 0,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 4,
  },
  sectionSubtitle: {
    fontSize: 13,
    color: colors.textSecondary,
    marginBottom: 14,
  },
  browseAllButton: {
    borderWidth: 1.5,
    borderColor: colors.primary,
    borderRadius: 10,
    paddingHorizontal: 28,
    paddingVertical: 12,
  },
  // Continue bar — replaces the old hero banner. Compact pill that taps
  // straight into the last opened movie.
  continueBar: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 16,
    marginTop: 14,
    marginBottom: 6,
    backgroundColor: colors.paper,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    paddingVertical: 8,
    paddingHorizontal: 12,
    gap: 12,
  },
  continueBarPoster: {
    width: 42,
    height: 42,
    borderRadius: 8,
  },
  continueBarLabel: {
    fontSize: 9,
    fontWeight: '800',
    color: colors.primary,
    letterSpacing: 1,
  },
  continueBarTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.text,
    marginTop: 1,
  },
  continueBarArrow: {
    fontSize: 12,
    color: colors.primary,
    marginLeft: 4,
  },
  browseAllText: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.primary,
  },
  homeTabToggleWrapper: {
    flexDirection: 'row',
    marginHorizontal: 16,
    marginTop: 20,
    backgroundColor: colors.paper,
    borderRadius: 12,
    padding: 4,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
  },
  homeTabToggleBtn: {
    flex: 1,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
  },
  homeTabToggleBtnActive: {
    backgroundColor: '#9c27b015',
  },
  homeTabToggleText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  homeTabToggleTextActive: {
    color: '#9c27b0',
  },
  levelPickerMenu: {
    position: 'absolute',
    top: 46,
    width: 180,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.paper,
    zIndex: 1000,
    elevation: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 12,
    overflow: 'hidden',
  },
  levelPickerItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  levelPickerItemActive: {
    backgroundColor: '#9c27b010',
  },
  levelPickerIcon: {
    fontSize: 14,
    marginRight: 10,
  },
  levelPickerText: {
    fontSize: 14,
    fontWeight: '500',
    color: colors.text,
  },
  levelPickerTextActive: {
    color: '#9c27b0',
    fontWeight: '700',
  },
  genreFilterBtn: {
    alignSelf: 'center',
    marginTop: 10,
    paddingHorizontal: 16,
    paddingVertical: 7,
    borderRadius: 16,
    backgroundColor: colors.paper,
    borderWidth: 1,
    borderColor: colors.border,
  },
  genreFilterText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.text,
  },
  levelSortRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
    marginTop: 4,
    marginBottom: 8,
    paddingHorizontal: 16,
  },
  levelSortChip: {
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: colors.paper,
    borderWidth: 1,
    borderColor: colors.border,
  },
  levelSortChipActive: {
    backgroundColor: '#9c27b015',
    borderColor: '#9c27b0',
  },
  levelSortText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  levelSortTextActive: {
    color: '#9c27b0',
  },
  skeletonContainer: {
    paddingTop: 4,
  },
  skeletonRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  skeletonPoster: {
    width: 60,
    height: 90,
    borderRadius: 6,
    backgroundColor: colors.border,
    marginRight: 14,
    marginLeft: 48,
  },
  skeletonInfo: {
    flex: 1,
  },
  skeletonLine: {
    height: 12,
    borderRadius: 4,
    backgroundColor: colors.border,
  },
  carousel: {
    paddingRight: 16,
  },
  featureGrid: {
    flexDirection: 'row',
    gap: 12,
  },
  featureCard: {
    flex: 1,
    backgroundColor: colors.paper,
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  featureIcon: {
    fontSize: 28,
    marginBottom: 8,
  },
  featureTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.text,
    textAlign: 'center',
  },
  featureDesc: {
    fontSize: 11,
    color: colors.textSecondary,
    textAlign: 'center',
    marginTop: 4,
  },
  loader: {
    paddingVertical: 40,
  },
  // Movie Detail Screen styles
  detailHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 8,
    backgroundColor: colors.paper,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  detailHeaderTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.text,
    flex: 1,
    textAlign: 'center',
  },
  backButton: {
    paddingVertical: 8,
    paddingRight: 12,
  },
  backButtonText: {
    fontSize: 16,
    color: colors.primary,
    fontWeight: '600',
  },
  loadingText: {
    fontSize: 18,
    fontWeight: '600',
    color: colors.text,
    marginTop: 20,
  },
  loadingSubtext: {
    fontSize: 14,
    color: colors.textSecondary,
    marginTop: 4,
  },
  errorText: {
    fontSize: 16,
    color: colors.error,
    textAlign: 'center',
    marginBottom: 20,
    paddingHorizontal: 20,
  },
  heroBackdrop: {
    position: 'relative',
    height: 240,
    overflow: 'hidden',
    backgroundColor: '#0a0612',
  },
  heroBackdropImage: {
    ...StyleSheet.absoluteFillObject,
  },
  heroTopFade: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 80,
  },
  heroBottomGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  heroFloating: {
    position: 'absolute',
    left: 14,
    right: 14,
    bottom: 12,
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 12,
  },
  heroPoster: {
    width: 76,
    height: 114,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: '#0a0612',
    shadowColor: '#000',
    shadowOpacity: 0.5,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 6 },
    elevation: 8,
  },
  heroPosterImage: {
    width: '100%',
    height: '100%',
  },
  heroMetaCol: {
    flex: 1,
    minWidth: 0,
  },
  heroTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#fff',
    letterSpacing: -0.4,
    lineHeight: 24,
  },
  heroMetaRow: {
    fontSize: 12,
    color: 'rgba(255,255,255,0.85)',
    marginTop: 4,
  },
  heroMetaYear: {
    fontSize: 12,
    color: 'rgba(255,255,255,0.85)',
    fontWeight: '600',
  },
  heroMetaRating: {
    fontSize: 12,
    color: 'rgba(255,255,255,0.95)',
    fontWeight: '700',
  },
  heroMetaGenres: {
    fontSize: 12,
    color: 'rgba(255,255,255,0.85)',
  },
  heroMetaSep: {
    fontSize: 12,
    color: 'rgba(255,255,255,0.6)',
  },
  heroDifficultyChip: {
    alignSelf: 'flex-start',
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 8,
    marginTop: 6,
  },
  heroDifficultyChipText: {
    fontSize: 11,
    color: '#fff',
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  posterZoomBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.9)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  posterZoomImage: {
    width: 320,
    height: 480,
  },
  posterShareBtn: {
    marginTop: 16,
    alignSelf: 'center',
    backgroundColor: 'rgba(255,255,255,0.15)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.35)',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 24,
  },
  posterShareBtnText: {
    color: '#FFF',
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: 0.3,
  },
  undoToast: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 24,
    alignItems: 'center',
    paddingHorizontal: 16,
  },
  undoToastInner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2E2E2E',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOpacity: 0.25,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 4,
    maxWidth: '92%',
  },
  undoToastText: {
    color: '#FFF',
    fontSize: 14,
    flexShrink: 1,
    marginRight: 16,
  },
  undoToastAction: {
    color: '#4FC3F7',
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  photosBtn: {
    alignSelf: 'flex-start',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
  photosBtnText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#fff',
  },
  overviewBox: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: colors.paper,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  overviewText: {
    fontSize: 13,
    color: colors.textSecondary,
    lineHeight: 19,
  },
  overviewToggle: {
    fontSize: 12,
    color: colors.primary,
    fontWeight: '600',
    marginTop: 6,
  },
  scriptErrorBox: {
    margin: 16,
    padding: 16,
    backgroundColor: colors.paper,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
  },
  scriptErrorText: {
    fontSize: 14,
    color: colors.textSecondary,
    textAlign: 'center',
    marginBottom: 12,
  },
  retryButton: {
    backgroundColor: colors.primary,
    paddingHorizontal: 24,
    paddingVertical: 10,
    borderRadius: 8,
  },
  retryButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  movieInfoStats: {
    fontSize: 13,
    color: colors.primary,
    fontWeight: '600',
  },
  // Unified vocabulary tabs (For You + A1–C2 + Idioms) — block style
  unifiedTabsRow: {
    flexDirection: 'row',
    paddingHorizontal: 6,
    paddingVertical: 6,
    gap: 2,
    alignItems: 'stretch',
  },
  unifiedTabsRowWrapper: {
    marginHorizontal: 12,
    marginTop: 4,
    marginBottom: 6,
    borderRadius: 12,
    backgroundColor: '#E4DCF0',
    overflow: 'hidden',
    position: 'relative',
  },
  unifiedTabsLeftFixed: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    flexDirection: 'row',
    alignItems: 'stretch',
    paddingLeft: 6,
    paddingVertical: 6,
    backgroundColor: '#E4DCF0',
    zIndex: 2,
  },
  unifiedTabsRightFade: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    right: 0,
    width: 28,
    zIndex: 1,
  },
  unifiedTabDivider: {
    width: 1,
    alignSelf: 'stretch',
    marginHorizontal: 4,
    marginVertical: 6,
    backgroundColor: colors.primary + '33',
  },
  unifiedTab: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    minWidth: 48,
  },
  unifiedTabLevel: {
    paddingHorizontal: 8,
    minWidth: 40,
  },
  unifiedTabIndicator: {
    position: 'absolute',
    top: 6,
    bottom: 6,
    borderRadius: 10,
  },
  unifiedTabLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.text,
    opacity: 0.5,
  },
  unifiedTabLabelActive: {
    opacity: 1,
  },
  countSortRow: {
    paddingTop: 8,
    paddingBottom: 6,
    paddingHorizontal: 16,
    alignItems: 'center',
  },
  countSortText: {
    fontSize: 13,
    color: colors.textSecondary,
  },
  levelDescription: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: colors.background,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  levelDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginRight: 8,
  },
  levelDescText: {
    fontSize: 14,
    color: colors.text,
    fontWeight: '600',
  },
  levelWordCount: {
    fontSize: 14,
    color: colors.textSecondary,
    marginLeft: 8,
  },
  // Word List - Polished design
  wordList: {
    paddingBottom: 40,
    backgroundColor: colors.paper,
  },
  wordSkeletonRow: {
    height: 50,
    marginBottom: 4,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(124, 92, 191, 0.10)',
    backgroundColor: 'rgba(124, 92, 191, 0.06)',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    gap: 12,
  },
  wordSkeletonBar: {
    height: 12,
    borderRadius: 4,
    backgroundColor: 'rgba(124, 92, 191, 0.18)',
  },
  wordSkeletonBarPrimary: {
    flex: 1,
  },
  wordSkeletonBarSecondary: {
    width: 28,
  },
  forYouEmpty: {
    textAlign: 'center',
    fontSize: 13,
    color: colors.textSecondary,
    paddingVertical: 10,
  },
  bottomBar: {
    flexDirection: 'row',
    backgroundColor: '#F3EEFF',
    borderTopWidth: 1,
    borderTopColor: '#E0D4F7',
    paddingTop: 7,
    paddingHorizontal: 16,
    gap: 6,
  },
  bottomBarBtn: {
    flex: 1,
    paddingVertical: 7,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
  },
  bottomBarBtnActive: {},
  bottomBarBtnText: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  bottomBarBtnTextActive: {
    color: colors.primary,
  },
  foryouMoreLink: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: 16,
    marginTop: 12,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.paper,
  },
  foryouMoreLinkText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.text,
    flex: 1,
  },
  foryouMoreLinkArrow: {
    fontSize: 18,
    fontWeight: '600',
    color: colors.primary,
    marginLeft: 12,
  },
  expandIcon: {
    fontSize: 10,
    color: colors.textSecondary,
    opacity: 0.5,
    marginLeft: 8,
  },
  expandIconRotated: {
    transform: [{ rotate: '180deg' }],
  },
  flagButton: {
    marginLeft: 4,
    padding: 4,
  },
  flagIcon: {
    fontSize: 16,
    color: colors.textSecondary,
    opacity: 0.5,
  },
  // Idiom Row styles
  idiomTypeBadge: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    marginLeft: 8,
  },
  phrasalVerbBadge: {
    backgroundColor: '#2196F3', // Blue for phrasal verbs
  },
  idiomBadge: {
    backgroundColor: colors.warning, // Orange for idioms
  },
  idiomTypeText: {
    fontSize: 10,
    fontWeight: '600',
    color: '#fff',
  },
  cefrBadge: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    marginLeft: 4,
  },
  cefrBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#fff',
  },
  idiomWordsText: {
    fontSize: 14,
    color: colors.textSecondary,
    flex: 1,
  },
  sentenceTranslationSkeleton: {
    height: 12,
    width: '60%',
    backgroundColor: colors.border,
    borderRadius: 4,
    marginTop: 6,
    opacity: 0.5,
  },
  exprTabsRow: {
    flexDirection: 'row',
    paddingHorizontal: 12,
    paddingVertical: 8,
    gap: 8,
  },
  exprTab: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: 'rgba(0,0,0,0.08)',
    backgroundColor: colors.paper,
    alignItems: 'center',
    justifyContent: 'center',
  },
  exprTabText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  listsCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.paper,
    borderRadius: 14,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  listsCardIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  listsCardName: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.text,
  },
  listsCardDesc: {
    fontSize: 12,
    color: colors.textSecondary,
    marginTop: 2,
  },
  listsCardBadge: {
    minWidth: 32,
    height: 28,
    paddingHorizontal: 10,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 8,
  },
  listsCardBadgeText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
  },
  stickyVocabHeader: {
    backgroundColor: colors.paper,
    paddingBottom: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 6,
    zIndex: 10,
  },
});
